--liquibase formatted sql

--changeset leto:61
CREATE TABLE user_tg
(
    id       BIGINT generated by default as identity primary key,
    name     TEXT   not null,
    msg_numb TEXT not null
);

CREATE TABLE message_tg
(
    id       BIGINT generated by default as identity primary key,
    date_time timestamp not null,
    user_id BIGINT references user_tg (id) on delete set null
);

CREATE TABLE volunteers
(
    id_volunteer      BIGINT generated by default as identity primary key,
   name_volunteer     TEXT   not null,
   last_name_volunteer     TEXT   not null,
    chat_id_volunteer long not null

);
